name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd jmeter && \
           docker build . --file Dockerfile -t godq/jmeter && \
           docker login -u godq -p dckr_pat_COfZBm8_9jLHtqV7debo4xn3YTw && \
           docker push godq/jmeter
           
    # - name: Build and push Jmeter Docker images
    #   # You may pin to the exact commit or the version.
    #   # uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
    #   uses: docker/build-push-action@v5.0.0
    #   with:
    #     # Build's context is the set of files located in the specified PATH or URL
    #     context: jmeter  # optional
    #     # Path to the Dockerfile
    #     file: jmeter/Dockerfile
    #     # List of metadata for an image
    #     labels: author:GodQ # optional
    #     # List of target platforms for build
    #     platforms: amd64,arm64 # optional
    #     # Always attempt to pull all referenced images
    #     pull: true # optional, default is false
    #     # Push is a shorthand for --output=type=registry
    #     push: true # optional, default is false
    #     # List of tags
    #     tags: latest # optional
